### ISSUE TITLE
Add Refresh Button

### ISSUE THREAD

**Issue by richardkeep** [devtical/nova-inspire#1]
This is an awesome package. It'd be nice if you add a refresh button at the top right corner that will will automatically reload the contents of the page without requiring full page refresh.

![reload](https://user-images.githubusercontent.com/3874381/54981683-fafdec80-4fb9-11e9-8d59-d994bbde640b.PNG)

**Comment by Kristories** [comment]
@richardkeep thanks for the idea. PRs wecome!

**Comment by Kristories** [comment]
[v1.1.0](https://github.com/Kristories/nova-inspire/releases/tag/v1.1.0) released!
